# Generated by Django 5.2.15 on 2026-09-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_ftploghmac_operateloghmac_passwordchangeloghmac_and_more'),
        ('audits', '0009_alter_passwordchangelog_datetime'),
    ]

    operations = [
    ]
