# Generated by Django 5.2.15 on 2026-09-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0011_commandhmac_sessionhmac'),
        ('terminal', '0011_endpoint_magnus_port'),
    ]

    operations = [
    ]
