# Generated by Django 4.1.13 on 2026-09-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ukey'),
        ('users', '0006_user_ukey_sn'),
    ]

    operations = [
    ]
